// Code generated by "stringer -linecomment -output cyclonedx_string.go -type MediaType"; DO NOT EDIT.

package cyclonedx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MediaTypeJSON-1]
	_ = x[MediaTypeXML-2]
	_ = x[MediaTypeProtobuf-3]
}

const _MediaType_name = "application/vnd.cyclonedx+jsonapplication/vnd.cyclonedx+xmlapplication/x.vnd.cyclonedx+protobuf"

var _MediaType_index = [...]uint8{0, 30, 59, 95}

func (i MediaType) String() string {
	i -= 1
	if i < 0 || i >= MediaType(len(_MediaType_index)-1) {
		return "MediaType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MediaType_name[_MediaType_index[i]:_MediaType_index[i+1]]
}
